<?php
use Illuminate\Database\Seeder;
class countrySeeder extends Seeder
{
/**
* Run the database seeds.
*
* @return void
*/
public function run()
{
	DB::table('countries')->truncate();
	$countries = array(
		array('id' => 1,'code' => 'AF' ,'name' => "Afghanistan",'phone_key' => 93),
		array('id' => 2,'code' => 'AL' ,'name' => "Albania",'phone_key' => 355),
		array('id' => 3,'code' => 'DZ' ,'name' => "Algeria",'phone_key' => 213),
		array('id' => 4,'code' => 'AS' ,'name' => "American Samoa",'phone_key' => 1684),
		array('id' => 5,'code' => 'AD' ,'name' => "Andorra",'phone_key' => 376),
		array('id' => 6,'code' => 'AO' ,'name' => "Angola",'phone_key' => 244),
		array('id' => 7,'code' => 'AI' ,'name' => "Anguilla",'phone_key' => 1264),
		array('id' => 8,'code' => 'AQ' ,'name' => "Antarctica",'phone_key' => 0),
		array('id' => 9,'code' => 'AG' ,'name' => "Antigua And Barbuda",'phone_key' => 1268),
		array('id' => 10,'code' => 'AR','name' => "Argentina",'phone_key' => 54),
		array('id' => 11,'code' => 'AM','name' => "Armenia",'phone_key' => 374),
		array('id' => 12,'code' => 'AW','name' => "Aruba",'phone_key' => 297),
		array('id' => 13,'code' => 'AU','name' => "Australia",'phone_key' => 61),
		array('id' => 14,'code' => 'AT','name' => "Austria",'phone_key' => 43),
		array('id' => 15,'code' => 'AZ','name' => "Azerbaijan",'phone_key' => 994),
		array('id' => 16,'code' => 'BS','name' => "Bahamas The",'phone_key' => 1242),
		array('id' => 17,'code' => 'BH','name' => "Bahrain",'phone_key' => 973),
		array('id' => 18,'code' => 'BD','name' => "Bangladesh",'phone_key' => 880),
		array('id' => 19,'code' => 'BB','name' => "Barbados",'phone_key' => 1246),
		array('id' => 20,'code' => 'BY','name' => "Belarus",'phone_key' => 375),
		array('id' => 21,'code' => 'BE','name' => "Belgium",'phone_key' => 32),
		array('id' => 22,'code' => 'BZ','name' => "Belize",'phone_key' => 501),
		array('id' => 23,'code' => 'BJ','name' => "Benin",'phone_key' => 229),
		array('id' => 24,'code' => 'BM','name' => "Bermuda",'phone_key' => 1441),
		array('id' => 25,'code' => 'BT','name' => "Bhutan",'phone_key' => 975),
		array('id' => 26,'code' => 'BO','name' => "Bolivia",'phone_key' => 591),
		array('id' => 27,'code' => 'BA','name' => "Bosnia and Herzegovina",'phone_key' => 387),
		array('id' => 28,'code' => 'BW','name' => "Botswana",'phone_key' => 267),
		array('id' => 29,'code' => 'BV','name' => "Bouvet Island",'phone_key' => 0),
		array('id' => 30,'code' => 'BR','name' => "Brazil",'phone_key' => 55),
		array('id' => 31,'code' => 'IO','name' => "British Indian Ocean Territory",'phone_key' => 246),
		array('id' => 32,'code' => 'BN','name' => "Brunei",'phone_key' => 673),
		array('id' => 33,'code' => 'BG','name' => "Bulgaria",'phone_key' => 359),
		array('id' => 34,'code' => 'BF','name' => "Burkina Faso",'phone_key' => 226),
		array('id' => 35,'code' => 'BI','name' => "Burundi",'phone_key' => 257),
		array('id' => 36,'code' => 'KH','name' => "Cambodia",'phone_key' => 855),
		array('id' => 37,'code' => 'CM','name' => "Cameroon",'phone_key' => 237),
		array('id' => 38,'code' => 'CA','name' => "Canada",'phone_key' => 1),
		array('id' => 39,'code' => 'CV','name' => "Cape Verde",'phone_key' => 238),
		array('id' => 40,'code' => 'KY','name' => "Cayman Islands",'phone_key' => 1345),
		array('id' => 41,'code' => 'CF','name' => "Central African Republic",'phone_key' => 236),
		array('id' => 42,'code' => 'TD','name' => "Chad",'phone_key' => 235),
		array('id' => 43,'code' => 'CL','name' => "Chile",'phone_key' => 56),
		array('id' => 44,'code' => 'CN','name' => "China",'phone_key' => 86),
		array('id' => 45,'code' => 'CX','name' => "Christmas Island",'phone_key' => 61),
		array('id' => 46,'code' => 'CC','name' => "Cocos (Keeling) Islands",'phone_key' => 672),
		array('id' => 47,'code' => 'CO','name' => "Colombia",'phone_key' => 57),
		array('id' => 48,'code' => 'KM','name' => "Comoros",'phone_key' => 269),
		array('id' => 49,'code' => 'CG','name' => "Congo",'phone_key' => 242),
		array('id' => 50,'code' => 'CD','name' => "Congo The Democratic Republic Of The",'phone_key' => 242),
		array('id' => 51,'code' => 'CK','name' => "Cook Islands",'phone_key' => 682),
		array('id' => 52,'code' => 'CR','name' => "Costa Rica",'phone_key' => 506),
		array('id' => 53,'code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phone_key' => 225),
		array('id' => 54,'code' => 'HR','name' => "Croatia (Hrvatska)",'phone_key' => 385),
		array('id' => 55,'code' => 'CU','name' => "Cuba",'phone_key' => 53),
		array('id' => 56,'code' => 'CY','name' => "Cyprus",'phone_key' => 357),
		array('id' => 57,'code' => 'CZ','name' => "Czech Republic",'phone_key' => 420),
		array('id' => 58,'code' => 'DK','name' => "Denmark",'phone_key' => 45),
		array('id' => 59,'code' => 'DJ','name' => "Djibouti",'phone_key' => 253),
		array('id' => 60,'code' => 'DM','name' => "Dominica",'phone_key' => 1767),
		array('id' => 61,'code' => 'DO','name' => "Dominican Republic",'phone_key' => 1809),
		array('id' => 62,'code' => 'TP','name' => "East Timor",'phone_key' => 670),
		array('id' => 63,'code' => 'EC','name' => "Ecuador",'phone_key' => 593),
		array('id' => 64,'code' => 'EG','name' => "Egypt",'phone_key' => 20),
		array('id' => 65,'code' => 'SV','name' => "El Salvador",'phone_key' => 503),
		array('id' => 66,'code' => 'GQ','name' => "Equatorial Guinea",'phone_key' => 240),
		array('id' => 67,'code' => 'ER','name' => "Eritrea",'phone_key' => 291),
		array('id' => 68,'code' => 'EE','name' => "Estonia",'phone_key' => 372),
		array('id' => 69,'code' => 'ET','name' => "Ethiopia",'phone_key' => 251),
		array('id' => 70,'code' => 'XA','name' => "External Territories of Australia",'phone_key' => 61),
		array('id' => 71,'code' => 'FK','name' => "Falkland Islands",'phone_key' => 500),
		array('id' => 72,'code' => 'FO','name' => "Faroe Islands",'phone_key' => 298),
		array('id' => 73,'code' => 'FJ','name' => "Fiji Islands",'phone_key' => 679),
		array('id' => 74,'code' => 'FI','name' => "Finland",'phone_key' => 358),
		array('id' => 75,'code' => 'FR','name' => "France",'phone_key' => 33),
		array('id' => 76,'code' => 'GF','name' => "French Guiana",'phone_key' => 594),
		array('id' => 77,'code' => 'PF','name' => "French Polynesia",'phone_key' => 689),
		array('id' => 78,'code' => 'TF','name' => "French Southern Territories",'phone_key' => 0),
		array('id' => 79,'code' => 'GA','name' => "Gabon",'phone_key' => 241),
		array('id' => 80,'code' => 'GM','name' => "Gambia The",'phone_key' => 220),
		array('id' => 81,'code' => 'GE','name' => "Georgia",'phone_key' => 995),
		array('id' => 82,'code' => 'DE','name' => "Germany",'phone_key' => 49),
		array('id' => 83,'code' => 'GH','name' => "Ghana",'phone_key' => 233),
		array('id' => 84,'code' => 'GI','name' => "Gibraltar",'phone_key' => 350),
		array('id' => 85,'code' => 'GR','name' => "Greece",'phone_key' => 30),
		array('id' => 86,'code' => 'GL','name' => "Greenland",'phone_key' => 299),
		array('id' => 87,'code' => 'GD','name' => "Grenada",'phone_key' => 1473),
		array('id' => 88,'code' => 'GP','name' => "Guadeloupe",'phone_key' => 590),
		array('id' => 89,'code' => 'GU','name' => "Guam",'phone_key' => 1671),
		array('id' => 90,'code' => 'GT','name' => "Guatemala",'phone_key' => 502),
		array('id' => 91,'code' => 'XU','name' => "Guernsey and Alderney",'phone_key' => 44),
		array('id' => 92,'code' => 'GN','name' => "Guinea",'phone_key' => 224),
		array('id' => 93,'code' => 'GW','name' => "Guinea-Bissau",'phone_key' => 245),
		array('id' => 94,'code' => 'GY','name' => "Guyana",'phone_key' => 592),
		array('id' => 95,'code' => 'HT','name' => "Haiti",'phone_key' => 509),
		array('id' => 96,'code' => 'HM','name' => "Heard and McDonald Islands",'phone_key' => 0),
		array('id' => 97,'code' => 'HN','name' => "Honduras",'phone_key' => 504),
		array('id' => 98,'code' => 'HK','name' => "Hong Kong S.A.R.",'phone_key' => 852),
		array('id' => 99,'code' => 'HU','name' => "Hungary",'phone_key' => 36),
		array('id' => 100,'code' => 'IS','name' => "Iceland",'phone_key' => 354),
		array('id' => 101,'code' => 'IN','name' => "India",'phone_key' => 91),
		array('id' => 102,'code' => 'ID','name' => "Indonesia",'phone_key' => 62),
		array('id' => 103,'code' => 'IR','name' => "Iran",'phone_key' => 98),
		array('id' => 104,'code' => 'IQ','name' => "Iraq",'phone_key' => 964),
		array('id' => 105,'code' => 'IE','name' => "Ireland",'phone_key' => 353),
		array('id' => 106,'code' => 'IL','name' => "Israel",'phone_key' => 972),
		array('id' => 107,'code' => 'IT','name' => "Italy",'phone_key' => 39),
		array('id' => 108,'code' => 'JM','name' => "Jamaica",'phone_key' => 1876),
		array('id' => 109,'code' => 'JP','name' => "Japan",'phone_key' => 81),
		array('id' => 110,'code' => 'XJ','name' => "Jersey",'phone_key' => 44),
		array('id' => 111,'code' => 'JO','name' => "Jordan",'phone_key' => 962),
		array('id' => 112,'code' => 'KZ','name' => "Kazakhstan",'phone_key' => 7),
		array('id' => 113,'code' => 'KE','name' => "Kenya",'phone_key' => 254),
		array('id' => 114,'code' => 'KI','name' => "Kiribati",'phone_key' => 686),
		array('id' => 115,'code' => 'KP','name' => "Korea North",'phone_key' => 850),
		array('id' => 116,'code' => 'KR','name' => "Korea South",'phone_key' => 82),
		array('id' => 117,'code' => 'KW','name' => "Kuwait",'phone_key' => 965),
		array('id' => 118,'code' => 'KG','name' => "Kyrgyzstan",'phone_key' => 996),
		array('id' => 119,'code' => 'LA','name' => "Laos",'phone_key' => 856),
		array('id' => 120,'code' => 'LV','name' => "Latvia",'phone_key' => 371),
		array('id' => 121,'code' => 'LB','name' => "Lebanon",'phone_key' => 961),
		array('id' => 122,'code' => 'LS','name' => "Lesotho",'phone_key' => 266),
		array('id' => 123,'code' => 'LR','name' => "Liberia",'phone_key' => 231),
		array('id' => 124,'code' => 'LY','name' => "Libya",'phone_key' => 218),
		array('id' => 125,'code' => 'LI','name' => "Liechtenstein",'phone_key' => 423),
		array('id' => 126,'code' => 'LT','name' => "Lithuania",'phone_key' => 370),
		array('id' => 127,'code' => 'LU','name' => "Luxembourg",'phone_key' => 352),
		array('id' => 128,'code' => 'MO','name' => "Macau S.A.R.",'phone_key' => 853),
		array('id' => 129,'code' => 'MK','name' => "Macedonia",'phone_key' => 389),
		array('id' => 130,'code' => 'MG','name' => "Madagascar",'phone_key' => 261),
		array('id' => 131,'code' => 'MW','name' => "Malawi",'phone_key' => 265),
		array('id' => 132,'code' => 'MY','name' => "Malaysia",'phone_key' => 60),
		array('id' => 133,'code' => 'MV','name' => "Maldives",'phone_key' => 960),
		array('id' => 134,'code' => 'ML','name' => "Mali",'phone_key' => 223),
		array('id' => 135,'code' => 'MT','name' => "Malta",'phone_key' => 356),
		array('id' => 136,'code' => 'XM','name' => "Man (Isle of)",'phone_key' => 44),
		array('id' => 137,'code' => 'MH','name' => "Marshall Islands",'phone_key' => 692),
		array('id' => 138,'code' => 'MQ','name' => "Martinique",'phone_key' => 596),
		array('id' => 139,'code' => 'MR','name' => "Mauritania",'phone_key' => 222),
		array('id' => 140,'code' => 'MU','name' => "Mauritius",'phone_key' => 230),
		array('id' => 141,'code' => 'YT','name' => "Mayotte",'phone_key' => 269),
		array('id' => 142,'code' => 'MX','name' => "Mexico",'phone_key' => 52),
		array('id' => 143,'code' => 'FM','name' => "Micronesia",'phone_key' => 691),
		array('id' => 144,'code' => 'MD','name' => "Moldova",'phone_key' => 373),
		array('id' => 145,'code' => 'MC','name' => "Monaco",'phone_key' => 377),
		array('id' => 146,'code' => 'MN','name' => "Mongolia",'phone_key' => 976),
		array('id' => 147,'code' => 'MS','name' => "Montserrat",'phone_key' => 1664),
		array('id' => 148,'code' => 'MA','name' => "Morocco",'phone_key' => 212),
		array('id' => 149,'code' => 'MZ','name' => "Mozambique",'phone_key' => 258),
		array('id' => 150,'code' => 'MM','name' => "Myanmar",'phone_key' => 95),
		array('id' => 151,'code' => 'NA','name' => "Namibia",'phone_key' => 264),
		array('id' => 152,'code' => 'NR','name' => "Nauru",'phone_key' => 674),
		array('id' => 153,'code' => 'NP','name' => "Nepal",'phone_key' => 977),
		array('id' => 154,'code' => 'AN','name' => "Netherlands Antilles",'phone_key' => 599),
		array('id' => 155,'code' => 'NL','name' => "Netherlands The",'phone_key' => 31),
		array('id' => 156,'code' => 'NC','name' => "New Caledonia",'phone_key' => 687),
		array('id' => 157,'code' => 'NZ','name' => "New Zealand",'phone_key' => 64),
		array('id' => 158,'code' => 'NI','name' => "Nicaragua",'phone_key' => 505),
		array('id' => 159,'code' => 'NE','name' => "Niger",'phone_key' => 227),
		array('id' => 160,'code' => 'NG','name' => "Nigeria",'phone_key' => 234),
		array('id' => 161,'code' => 'NU','name' => "Niue",'phone_key' => 683),
		array('id' => 162,'code' => 'NF','name' => "Norfolk Island",'phone_key' => 672),
		array('id' => 163,'code' => 'MP','name' => "Northern Mariana Islands",'phone_key' => 1670),
		array('id' => 164,'code' => 'NO','name' => "Norway",'phone_key' => 47),
		array('id' => 165,'code' => 'OM','name' => "Oman",'phone_key' => 968),
		array('id' => 166,'code' => 'PK','name' => "Pakistan",'phone_key' => 92),
		array('id' => 167,'code' => 'PW','name' => "Palau",'phone_key' => 680),
		array('id' => 168,'code' => 'PS','name' => "Palestinian Territory Occupied",'phone_key' => 970),
		array('id' => 169,'code' => 'PA','name' => "Panama",'phone_key' => 507),
		array('id' => 170,'code' => 'PG','name' => "Papua new Guinea",'phone_key' => 675),
		array('id' => 171,'code' => 'PY','name' => "Paraguay",'phone_key' => 595),
		array('id' => 172,'code' => 'PE','name' => "Peru",'phone_key' => 51),
		array('id' => 173,'code' => 'PH','name' => "Philippines",'phone_key' => 63),
		array('id' => 174,'code' => 'PN','name' => "Pitcairn Island",'phone_key' => 0),
		array('id' => 175,'code' => 'PL','name' => "Poland",'phone_key' => 48),
		array('id' => 176,'code' => 'PT','name' => "Portugal",'phone_key' => 351),
		array('id' => 177,'code' => 'PR','name' => "Puerto Rico",'phone_key' => 1787),
		array('id' => 178,'code' => 'QA','name' => "Qatar",'phone_key' => 974),
		array('id' => 179,'code' => 'RE','name' => "Reunion",'phone_key' => 262),
		array('id' => 180,'code' => 'RO','name' => "Romania",'phone_key' => 40),
		array('id' => 181,'code' => 'RU','name' => "Russia",'phone_key' => 70),
		array('id' => 182,'code' => 'RW','name' => "Rwanda",'phone_key' => 250),
		array('id' => 183,'code' => 'SH','name' => "Saint Helena",'phone_key' => 290),
		array('id' => 184,'code' => 'KN','name' => "Saint Kitts And Nevis",'phone_key' => 1869),
		array('id' => 185,'code' => 'LC','name' => "Saint Lucia",'phone_key' => 1758),
		array('id' => 186,'code' => 'PM','name' => "Saint Pierre and Miquelon",'phone_key' => 508),
		array('id' => 187,'code' => 'VC','name' => "Saint Vincent And The Grenadines",'phone_key' => 1784),
		array('id' => 188,'code' => 'WS','name' => "Samoa",'phone_key' => 684),
		array('id' => 189,'code' => 'SM','name' => "San Marino",'phone_key' => 378),
		array('id' => 190,'code' => 'ST','name' => "Sao Tome and Principe",'phone_key' => 239),
		array('id' => 191,'code' => 'SA','name' => "Saudi Arabia",'phone_key' => 966),
		array('id' => 192,'code' => 'SN','name' => "Senegal",'phone_key' => 221),
		array('id' => 193,'code' => 'RS','name' => "Serbia",'phone_key' => 381),
		array('id' => 194,'code' => 'SC','name' => "Seychelles",'phone_key' => 248),
		array('id' => 195,'code' => 'SL','name' => "Sierra Leone",'phone_key' => 232),
		array('id' => 196,'code' => 'SG','name' => "Singapore",'phone_key' => 65),
		array('id' => 197,'code' => 'SK','name' => "Slovakia",'phone_key' => 421),
		array('id' => 198,'code' => 'SI','name' => "Slovenia",'phone_key' => 386),
		array('id' => 199,'code' => 'XG','name' => "Smaller Territories of the UK",'phone_key' => 44),
		array('id' => 200,'code' => 'SB','name' => "Solomon Islands",'phone_key' => 677),
		array('id' => 201,'code' => 'SO','name' => "Somalia",'phone_key' => 252),
		array('id' => 202,'code' => 'ZA','name' => "South Africa",'phone_key' => 27),
		array('id' => 203,'code' => 'GS','name' => "South Georgia",'phone_key' => 0),
		array('id' => 204,'code' => 'SS','name' => "South Sudan",'phone_key' => 211),
		array('id' => 205,'code' => 'ES','name' => "Spain",'phone_key' => 34),
		array('id' => 206,'code' => 'LK','name' => "Sri Lanka",'phone_key' => 94),
		array('id' => 207,'code' => 'SD','name' => "Sudan",'phone_key' => 249),
		array('id' => 208,'code' => 'SR','name' => "Suriname",'phone_key' => 597),
		array('id' => 209,'code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phone_key' => 47),
		array('id' => 210,'code' => 'SZ','name' => "Swaziland",'phone_key' => 268),
		array('id' => 211,'code' => 'SE','name' => "Sweden",'phone_key' => 46),
		array('id' => 212,'code' => 'CH','name' => "Switzerland",'phone_key' => 41),
		array('id' => 213,'code' => 'SY','name' => "Syria",'phone_key' => 963),
		array('id' => 214,'code' => 'TW','name' => "Taiwan",'phone_key' => 886),
		array('id' => 215,'code' => 'TJ','name' => "Tajikistan",'phone_key' => 992),
		array('id' => 216,'code' => 'TZ','name' => "Tanzania",'phone_key' => 255),
		array('id' => 217,'code' => 'TH','name' => "Thailand",'phone_key' => 66),
		array('id' => 218,'code' => 'TG','name' => "Togo",'phone_key' => 228),
		array('id' => 219,'code' => 'TK','name' => "Tokelau",'phone_key' => 690),
		array('id' => 220,'code' => 'TO','name' => "Tonga",'phone_key' => 676),
		array('id' => 221,'code' => 'TT','name' => "Trinidad And Tobago",'phone_key' => 1868),
		array('id' => 222,'code' => 'TN','name' => "Tunisia",'phone_key' => 216),
		array('id' => 223,'code' => 'TR','name' => "Turkey",'phone_key' => 90),
		array('id' => 224,'code' => 'TM','name' => "Turkmenistan",'phone_key' => 7370),
		array('id' => 225,'code' => 'TC','name' => "Turks And Caicos Islands",'phone_key' => 1649),
		array('id' => 226,'code' => 'TV','name' => "Tuvalu",'phone_key' => 688),
		array('id' => 227,'code' => 'UG','name' => "Uganda",'phone_key' => 256),
		array('id' => 228,'code' => 'UA','name' => "Ukraine",'phone_key' => 380),
		array('id' => 229,'code' => 'AE','name' => "United Arab Emirates",'phone_key' => 971),
		array('id' => 230,'code' => 'GB','name' => "United Kingdom",'phone_key' => 44),
		array('id' => 231,'code' => 'US','name' => "United States",'phone_key' => 1),
		array('id' => 232,'code' => 'UM','name' => "United States Minor Outlying Islands",'phone_key' => 1),
		array('id' => 233,'code' => 'UY','name' => "Uruguay",'phone_key' => 598),
		array('id' => 234,'code' => 'UZ','name' => "Uzbekistan",'phone_key' => 998),
		array('id' => 235,'code' => 'VU','name' => "Vanuatu",'phone_key' => 678),
		array('id' => 236,'code' => 'VA','name' => "Vatican City State (Holy See)",'phone_key' => 39),
		array('id' => 237,'code' => 'VE','name' => "Venezuela",'phone_key' => 58),
		array('id' => 238,'code' => 'VN','name' => "Vietnam",'phone_key' => 84),
		array('id' => 239,'code' => 'VG','name' => "Virgin Islands (British)",'phone_key' => 1284),
		array('id' => 240,'code' => 'VI','name' => "Virgin Islands (US)",'phone_key' => 1340),
		array('id' => 241,'code' => 'WF','name' => "Wallis And Futuna Islands",'phone_key' => 681),
		array('id' => 242,'code' => 'EH','name' => "Western Sahara",'phone_key' => 212),
		array('id' => 243,'code' => 'YE','name' => "Yemen",'phone_key' => 967),
		array('id' => 244,'code' => 'YU','name' => "Yugoslavia",'phone_key' => 38),
		array('id' => 245,'code' => 'ZM','name' => "Zambia",'phone_key' => 260),
		array('id' => 246,'code' => 'ZW','name' => "Zimbabwe",'phone_key' => 263),
		);
		DB::table('countries')->insert($countries);
	}
}